### ISSUE TITLE
InfoBar 重载后CloseButton的前景色 & IsClosable="False"后摆放位置问题

### ISSUE THREAD

**Issue by Yue-cn** [wherewhere/ModernWpf#10]
### 触发方法:重载

正常CloseButton的前景色
![image](https://user-images.githubusercontent.com/79188080/177124469-67da45c5-9063-48df-9451-dcb79b582085.png)
After:::::
![image](https://user-images.githubusercontent.com/79188080/177124514-ca2495ff-5f62-42c3-8778-a7dae116b4d3.png)

**IsClosable**
正常:::
![image](https://user-images.githubusercontent.com/79188080/177124618-7378f94e-eab9-4381-9466-d0f897bbe32e.png)
After:::::::
![image](https://user-images.githubusercontent.com/79188080/177124646-aad603a7-379c-4f31-add4-739bc449e787.png)

**Comment by wherewhere** [comment]
你更新一下版本。。。

**Comment by AYue2021** [comment]
> Owner

最近更新?挺快的,如果修了,就Close吧

**Comment by wherewhere** [comment]
可能没修，可能修了。。。

**Comment by AYue2021** [comment]
两排的方法是把窗口缩小,会自己折下来,
但是又折不回去了

**Comment by wherewhere** [comment]
能用就行了，我睡觉前移植的。。。
