### ISSUE TITLE
Regressions (broken dark theme)

### ISSUE THREAD

**Issue by Valkirie** [wherewhere/ModernWpf#23]
Commit: https://github.com/wherewhere/ModernWpf/commit/ecafdc3e362baf6937125cc7a3b00f9a1b06e56b, has broken Dark theme.

**Comment by wherewhere** [comment]
。。。

**Comment by wherewhere** [comment]
I give up...

**Comment by wherewhere** [comment]
But it work fine in my program, or I will not commit it...

**Comment by wherewhere** [comment]
Maybe we can create a new project to create a real WinUI for WPF. And collect more developers to work on it.
