### ISSUE TITLE
NavigationViewItem  Icon显示问题

### ISSUE THREAD

**Issue by Yue-cn** [wherewhere/ModernWpf#7]
NavigationViewItem 在没有Segoe MDL2 Assets字体的电脑上会显示方块
![image](https://user-images.githubusercontent.com/79188080/177092202-f030f10c-b695-4b10-a74f-aed2e21e0efe.png)

**Comment by YujunA** [comment]
> NavigationViewItem 在没有Segoe MDL2 Assets字体的电脑上会显示方块
> ![image](https://user-images.githubusercontent.com/79188080/177092202-f030f10c-b695-4b10-a74f-aed2e21e0efe.png)
> 

是的，在w7，8.1上很明显。建议把segmdl2转换成geometry放在path里会更好。

**Comment by wherewhere** [comment]
请使用FluentIcon
